### PR TITLE
Fix issues with deleting originals and converts HEIC files regardless of capitalization

### PR DESCRIPTION
**Pull request by KaylaPP**

### CODE REVIEW

**Comment by shihaocao** [comment]
Hey kevin, thanks for opening this PR, can we delete both the original and the auxiliary file? as in have command calls to delete both?

**Comment by KaylaPP** [comment]
Do you mean allowing the user the ability to pass in command line arguments to allow for the deletion of either file type?

**Comment by shihaocao** [comment]
I think for me, It generates the auxiliary file as I outlined, so if you'd like to add deletion of the original files, which I'm down for, can you make sure to have delete calls for both?

**Comment by shihaocao** [comment]
Aight lmao I'm just gonna merge it. And then make my own requested changes haha

**Comment by shihaocao** [comment]
Thank you for this contribution though! Let me know if forwhatever reason my stuff breaks it

**Comment by KaylaPP** [comment]
Haha of course. I got busy over the past day or so.

**Comment by shihaocao** [comment]
Okay cleaned some of the stuff up, also added multithreading just for fun haha

**Pull request merged**
